### ISSUE TITLE
Possible release date 

### ISSUE THREAD

**Issue by pourfard** [aim-uofa/Matcher#1]
Hi, thanks for the great article 
May I ask you what time are you going to release the source code? Will you release the pretrained models too?

**Comment by lihengtao** [comment]
Hi, thanks for your interest. We are preparing for the open source and will release both the code and models. Please stay tuned.:)

**Comment by tensorboy** [comment]
Good work, looking forward to the code and pre-trained models.

**Comment by ha1ha2hahaha** [comment]
Hi，thanks for your great work! when I used the DINOv2 as a backbone, it would give a 1024 embedding as a ouput.But you've written that it will give a tensor with the size of h*w*c. Could you tell me why?

**Comment by lihengtao** [comment]
> Hi，thanks for your great work! when I used the DINOv2 as a backbone, it would give a 1024 embedding as a ouput.But you've written that it will give a tensor with the size of h_w_c. Could you tell me why?

Hi, you can call DinoVisionTransformer.forward_features to get a dict which contains class token and patch tokens. You can refer  https://github.com/facebookresearch/dinov2/blob/main/dinov2/models/vision_transformer.py#LL233C22-L233C22 to get more details. :)

**Comment by ha1ha2hahaha** [comment]
> 
thank you！

**Comment by leolle** [comment]
> Hi, thanks for your interest. We are preparing for the open source and will release both the code and models. Please stay tuned.:)

加油！

**Comment by tieguanyin803** [comment]
thanks for the great article

**Comment by evolu8** [comment]
Great work. Looking forward to the release.

**Comment by Jingxi245** [comment]
Hello, could you provide the codes and pre-trained models for testing? I want to test using my own data sets.

**Comment by NielsRogge** [comment]
For those waiting for the release, check out PerSAM (personalized SAM) which is already open-source, I made 2 tutorial notebooks for it here: https://github.com/NielsRogge/Transformers-Tutorials/tree/master/PerSAM

The Matcher authors do compare against PerSAM in their paper

**Comment by SSUHan** [comment]
Any update? I'm also looking forward to the release!

**Comment by zzzyzh** [comment]
Please tell me there's a relevant announcement date now, really looking forward to it!

**Comment by feivelliu** [comment]
When will it be updated?

**Comment by simoneangarano** [comment]
When are you publishing the code?

**Comment by yangliu96** [comment]
The code has been released. Thank you for your attention!
