### ISSUE TITLE
problem about dataset

### ISSUE THREAD

**Issue by duoqingxiaowangzi** [aim-uofa/Matcher#14]
![image](https://github.com/aim-uofa/Matcher/assets/117001352/72390272-a97a-4db4-a395-d92b2cadbf17)
hello, could you please tell me where is the splits fold, should i download it, or the code will make the folder once i run the code?

**Comment by yangliu96** [comment]
We offer the splits [here](https://github.com/aim-uofa/Matcher/tree/main/datasets/COCO2014/splits) .

**Comment by duoqingxiaowangzi** [comment]
oh, sorry about that, I didn't notice here. Thank you!
