### ISSUE TITLE
COCO-20 Dataset Mask Annotation

### ISSUE THREAD

**Issue by Spritea** [aim-uofa/Matcher#16]
Hi, thanks for this great work!

I tried to test Matcher on COCO-20<sup>i</sup> by following the command [here](https://github.com/aim-uofa/Matcher/blob/main/GETTING_STARTED.md#test-one-shot-semantic-segmentation) but I got following errors.

`
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/COCO2014/annotations/val2014/COCO_val2014_000000507081.png'
`

I believe this is because the code requires the COCO-20<sup>i</sup> mask annotation to be in image format, but the official annotation is in json format.

Could you please check it and provide the converted image format of the mask annotation as well, thank you so much!

**Comment by yangliu96** [comment]
Hi, we have included the instructions for downloading COCO annotations [here](https://github.com/aim-uofa/Matcher/tree/main/datasets), following [HSNet](https://github.com/juhongm999/hsnet).

You can download COCO2014 train/val annotations from this Google Drive: [train2014.zip](https://drive.google.com/file/d/1cwup51kcr4m7v9jO14ArpxKMA4O3-Uge/view?usp=sharing), [val2014.zip](https://drive.google.com/file/d/1PNw4U3T2MhzAEBWGGgceXvYU3cZ7mJL1/view?usp=sharing). (and locate both train2014/ and val2014/ under annotations/ directory).

**Comment by Spritea** [comment]
Thanks for the prompt help! The new label in image format works.
