### ISSUE TITLE
inference code

### ISSUE THREAD

**Issue by jwx15** [aim-uofa/Matcher#27]
你好，这个代码是不是没有提供推理的部分啊，如何推理自己的图片呢

**Comment by yangliu96** [comment]
您好！我们提供了一个Gradio Demo可以测试自己的图片。如果要想批量处理，可以仿照已有的Dataset构建自己的CustomDataset。

**Comment by jwx15** [comment]
您好，我看read.me文件后面放了个视频，这个代码是不是也能推理视频啊

**Comment by yangliu96** [comment]
Video推理我们近期会尽快放出来，当前只支持对图片的推理

**Comment by jwx15** [comment]
好的，谢谢
