### ISSUE TITLE
Matcher running very slowly, I suggest researchers give up this method.

### ISSUE THREAD

**Issue by wzp8023391** [aim-uofa/Matcher#29]
I have carefully tested the so-called Mathcer, but I found that this method running very very slowly, which means that this is a useless tool for researchers. Anyway, thanks the authors' work.

**Comment by yangliu96** [comment]
The academic value of Matcher lies in its insight that VFMs can be utilized to perform in-context segmentation tasks without training. Although the current version of Matcher has some limitations that need improvement, researchers can start from here to continuously enhance Matcher in terms of performance, inference speed, and applications, analogous to the progression from RCNN to Fast RCNN to Faster RCNN to Mask RCNN. We believe that Matcher is a research paradigm worth in-depth exploration in the era of large models. Additionally, we appreciate your thoughts on Matcher and hope you maintain a positive research mindset. We wish you success in your scientific endeavors.
