### ISSUE TITLE
Semantic segment

### ISSUE THREAD

**Issue by zzzyzh** [aim-uofa/Matcher#4]
Thank you for your outstanding work!

The paper mentions that you use SAM as the class-agnostic segmentation model, does this mean that Matcher does not have the ability to recognize semantic information while segmenting?

In the meantime, I'm curious as to when the source code will be released.

Your excellent will be a great help to my research!

**Comment by yangliu96** [comment]
Thanks for your interest.

Matcher is a one-shot segmentation framework based on the vision foundation models (DINOv2 and SAM), and the semantic information of the segment results is consistent with the semantic categories provided by the reference. This is similar to in-context learning used by SegGPT (https://github.com/baaivision/Painter/tree/main/SegGPT). The all-purposed visual features extraction model, DINOv2, makes up for SAM's lack of semantic information.

We are organizing the source code.  It will be very soon. Please stay tuned.:)
