### ISSUE TITLE
Patch Level

### ISSUE THREAD

**Issue by zzzyzh** [aim-uofa/Matcher#6]
Thank you for your outstanding work!

Can you please describe how patch-level features are generated and how they are sized?
Also, I'd like to ask what the center prompt means and how the model generates it.

Your excellent will be a great help to my research!

**Comment by yangliu96** [comment]
Thank you for your interest！

For example, given an image with the size of (518, 518), the image encoder (we adopt DINOv2, a pre-trained ViT model, by default) with 14 $\times$ 14 patch_size will encode the image into patch-level feature sized by (518/14, 518/14). You can find the details of DINOv2 [here](https://github.com/facebookresearch/dinov2/blob/c3c2683a13cde94d4d99f523cf4170384b00c34c/dinov2/models/vision_transformer.py#L221).

The center prompts are the point prompt that encourages SAM to segment the object covering the whole image. First, we can obtain the matched points by Patch-level Matching. Then, we cluster the matched points based on their locations into K clusters with k-means++ (You can use other clustering algorithms), and we can obtain K cluster centers. The center prompts are sampled within these cluster centers.

**Comment by zzzyzh** [comment]
Thank you for your patience and kindness!
